# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"extract_zip_files": "00_utils.ipynb",
         "dir_leaderboard": "00_utils.ipynb",
         "competition": "00_utils.ipynb",
         "compressed_leaderboard_file": "00_utils.ipynb",
         "fname_leaderboard": "00_utils.ipynb",
         "display_all": "00_utils.ipynb",
         "show_leaderboard": "00_utils.ipynb",
         "dir_raw_data": "01_preprocessing.ipynb",
         "compressed_data_file": "01_preprocessing.ipynb",
         "train_path": "01_preprocessing.ipynb",
         "test_path": "01_preprocessing.ipynb",
         "dep_var": "01_preprocessing.ipynb",
         "show_dep_var": "01_preprocessing.ipynb",
         "cont_names": "01_preprocessing.ipynb",
         "show_na_share": "01_preprocessing.ipynb",
         "impute_continuous": "01_preprocessing.ipynb",
         "cat_names": "01_preprocessing.ipynb",
         "impute_categorical": "01_preprocessing.ipynb",
         "do_sample": "01_preprocessing.ipynb",
         "get_split": "01_preprocessing.ipynb",
         "clean_data_path": "01_preprocessing.ipynb",
         "clean_test_data_path": "01_preprocessing.ipynb",
         "clean_data_path_feather": "01_preprocessing.ipynb",
         "clean_test_data_path_feather": "01_preprocessing.ipynb",
         "inspect_category_mappings": "02_modelling.ipynb",
         "model_data_path": "02_modelling.ipynb",
         "mish": "02_modelling.ipynb",
         "Mish": "02_modelling.ipynb",
         "TabularModel.__init__": "02_modelling.ipynb",
         "predictions_vs_true_distribution_plots": "02_modelling.ipynb",
         "get_df_preds": "03_model_inspection.ipynb",
         "distribution_similarity": "03_model_inspection.ipynb",
         "element_comp": "03_model_inspection.ipynb",
         "get_categorical_freqs_single_col": "03_model_inspection.ipynb",
         "plot_best_vs_worst_categorical": "03_model_inspection.ipynb",
         "plot_top_distributions": "03_model_inspection.ipynb",
         "get_continuous_freqs_single_col": "03_model_inspection.ipynb",
         "plot_best_vs_worst_continuous": "03_model_inspection.ipynb",
         "get_all_continuous_freqs": "03_model_inspection.ipynb",
         "FastaiModel": "03_model_inspection.ipynb"}

modules = ["utils.py",
           "preprocessing.py",
           "modelling.py",
           "inspection.py"]

doc_url = "https://eschmidt42.github.io/kaggle_house_prices/"

git_url = "https://github.com/eschmidt42/kaggle_house_prices/tree/master/"

def custom_doc_links(name): return None
