# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"mish": "modelling.ipynb",
         "Mish": "modelling.ipynb",
         "predictions_vs_true_distribution_plots": "modelling.ipynb",
         "do_sample": "preprocessing.ipynb",
         "get_split": "preprocessing.ipynb",
         "extract_zip_files": "utils.ipynb",
         "display_all": "utils.ipynb",
         "show_leaderboard": "utils.ipynb"}

modules = ["modelling.py",
           "preprocessing.py",
           "utils.py"]

doc_url = "https://eschmidt42.github.io/src/"

git_url = "https://github.com/eschmidt42/src/tree/master/"

def custom_doc_links(name): return None
