# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"extract_zip_files": "00_utils.ipynb",
         "display_all": "00_utils.ipynb",
         "show_leaderboard": "00_utils.ipynb",
         "do_sample": "01_preprocessing.ipynb",
         "get_split": "01_preprocessing.ipynb",
         "mish": "02_modelling.ipynb",
         "Mish": "02_modelling.ipynb",
         "predictions_vs_true_distribution_plots": "02_modelling.ipynb"}

modules = ["utils.py",
           "preprocessing.py",
           "modelling.py"]

doc_url = "https://eschmidt42.github.io/src/"

git_url = "https://github.com/eschmidt42/src/tree/master/"

def custom_doc_links(name): return None
