# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_preprocessing.ipynb (unless otherwise specified).

__all__ = ['do_sample', 'get_split']

# Cell
from zipfile import ZipFile
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from .utils import *

# Cell
def do_sample(df:pd.DataFrame, small_sample:bool, n:int=100) -> pd.DataFrame:
    if small_sample:
        _df = df.sample(n=n)
    else:
        _df = df.copy(deep=True)
    return _df

# Cell
def get_split(df:pd.DataFrame, valid_pct:float=.2) -> pd.DataFrame:
    "Splitting the data frame into train and validation set, creating a new `valid` column"
    valid_idx = np.arange(int((1-valid_pct)*len(df)), len(df))
    train_idx = np.setdiff1d(np.arange(len(df)), valid_idx)
    df["valid"] = False
    df.iloc[valid_idx, df.columns.get_loc("valid")] = True
    return df